#!/bin/bash

#SBATCH -A IscrC_DIANA
#SBATCH -p boost_usr_prod
#SBATCH --qos boost_qos_dbg
#SBATCH --time=00:30:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=32
#SBATCH --gres=gpu:1
#SBATCH --mem=0
#SBATCH --exclusive
#SBATCH --job-name=run
#SBATCH --out=train_siamese_complete_test.out
#SBATCH --err=train_siamese_complete_test.out

srun ./test_new_complete_exe $@