#!/bin/bash

#SBATCH -A IscrC_DIANA
#SBATCH -p boost_usr_prod
#SBATCH --qos boost_qos_lprod
#SBATCH --time=4-00:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=32
#SBATCH --gres=gpu:4
#SBATCH --mem=0
#SBATCH --exclusive
#SBATCH --job-name=run
#SBATCH --out=train_siamese.out
#SBATCH --err=train_siamese.out

srun ./train_siamese_exe $@