scorer:
  uri: bolt://localhost:7687
  user: neo4j
  pwd: admin
  db: ret
  node_t: Artwork
  save: True
  out_dir: data/interim/scorer/test
mapping_file: data/processed/proj/test.csv
general:
  mode: random
  split: test
  num_couples: 1_000_000
  out_dir: data/processed/scores/
  seed: 1