scorer:
  uri: bolt://localhost:7687
  user: neo4j
  pwd: admin
  db: ret
  node_t: Artwork
  save: True
  out_dir: data/interim/scorer/val
mapping_file: data/processed/proj/val.csv
general:
  mode: random
  split: val
  max_entries_per_category: 3
  out_dir: data/processed/scores/
  seed: 1