model:
  params:
    in_channels: &h_dim 512
    hidden_channels: *h_dim
    ff_channels: *h_dim
    out_channels: *h_dim
    num_heads: 8
    dropout: 0.48
  state_dict: data/models/artwork_siamese_network_complete/fusion_module.pt
auxiliary_models_cat:
  text: #image 2 text model
    params:
      in_channels: *h_dim
      out_channels: *h_dim
      act: relu
      dropout: 0.06
      n_layers: 2
      strategy: 1
    state_dict: data/models/feat_proj_image_text/model_6.pt
  graph: #image 2 graph model
    params:
      in_channels: *h_dim
      out_channels: *h_dim
      act: relu
      dropout: 0.26
      n_layers: 1
      strategy: 1
    state_dict: data/models/feat_proj_image_text/model_6.pt

auxiliary_models_query:
  image: # text 2 image
    params:
      in_channels: *h_dim
      out_channels: *h_dim
      act: relu
      dropout: 0.01
      n_layers: 2
      strategy: 2
    state_dict: data/models/feat_proj_image_text/model_6.pt
  graph: # text 2 graph
    params:
      in_channels: *h_dim
      out_channels: *h_dim
      act: relu
      dropout: 0.43
      n_layers: 2
      strategy: 0
    state_dict: data/models/feat_proj_image_text/model_3.pt

dataset:
  catalogue:
    params:
      names: &csv_file data/processed/proj/test.csv
      modalities: [text]
      data_dir: &data_dir data/processed/complete_embeddings
  test:
    params:
      names: *csv_file
      modalities: [image]
      data_dir: *data_dir
dataloader:
  batch_size: 128
  num_workers: 16
  shuffle: False
  drop_last: False

metrics:
  recall_at_1:
    type: RetrievalRecall
    params:
      top_k: 1
  recall_at_5:
    type: RetrievalRecall
    params:
      top_k: 5
  recall_at_10:
    type: RetrievalRecall
    params:
      top_k: 10
encoding:
  pbar: &pbar rTrue
  device: &device cuda

test_loop:
  pbar: *pbar
  device: *device
