model:
  in_channels: 512
  out_channels: 512
  act: relu
dataset:
  train:
    source_modality: image
    dest_modality: text
    data_source_dir: ../../data/raw/images-resized
    preprocess_source:
      RandomHorizontalFlip:
        p: 0.5
      RandomPerspective:
        distortion_scale: 0.6
        p: 0.5
    preprocess_dest:
      SynonymAug:
        aug_src: wordnet
        aug_p: 0.2
      RandomWordAug:
        action: delete
        aug_p: 0.2
    data: ../../data/processed/proj/train.csv
  val:
    source_modality: image
    dest_modality: text
    preprocess_source: auto
    preprocess_dest: auto
    data_source_dir: ../../data/raw/images-resized
    data: ../../data/processed/proj/val.csv
  test:
    source_modality: image
    dest_modality: text
    data_source_dir: ../../data/raw/images-resized
    preprocess_source: auto
    preprocess_dest: auto
    data: ../../data/processed/proj/test.csv
dataloader:
  shuffle: True
  drop_last: False
optimizer:
  weight_decay: 0.0001
scheduler:
  factor: 0.1
  patience: 2
  verbose: False
early_stop:
  patience: 10
  verbose: False
general:
  device: cuda
  num_epochs: 150
  verbose: True
  pbar: False
hyperopt:
  model__strategy:
    type: choice
    range: [0, 1, 2]
  model__n_layers:
    type: choice
    range: [1, 2, 3]
  model__dropout:
    type: uniform
    range: [0.0, 0.5]
  dataloader__batch_size:
    type: choice
    range: [32, 64, 128]
  optimizer__lr:
    type: uniform
    range: [0.0001, 0.001]
  general__accum_iter:
    type: choice
    range: [5, 10, 15]
n_trials: 20
out_dir: ../../data/models/feat_proj_image_text
progress_bar: True

