model:
  params:
    fusion_in_channels: &h_dim 512
    fusion_hidden_channels: *h_dim
    fusion_ff_channels: *h_dim
    fusion_out_channels: *h_dim
    fusion_num_heads: 4
    dropout: 0.0
    strategy: 2
    num_layers: 1
  state_dict: data/models/artwork_siamese_network_complete/14/model.safetensors
auxiliary_models_cat:
  image: # text2img
    params:
      in_channels: *h_dim
      out_channels: *h_dim
      act: tanh
      dropout: 0.15
      n_layers: 1
      strategy: 0
    state_dict: data/models/feat_proj_text_image/model_3.pt
  graph: # text2graph
    params:
      in_channels: *h_dim
      out_channels: *h_dim
      act: tanh
      dropout: 0.27
      n_layers: 1
      strategy: 2
    state_dict: data/models/feat_proj_text_graph/model_9.pt

auxiliary_models_query:
  image: # image2txt
    params:
      in_channels: *h_dim
      out_channels: *h_dim
      act: tanh
      dropout: 0.29
      n_layers: 3
      strategy: 2
    state_dict: data/models/feat_proj_image_text/model_5.pt
  graph: # text 2 graph
    params:
      in_channels: *h_dim
      out_channels: *h_dim
      act: tanh
      dropout: 0.43
      n_layers: 1
      strategy: 2
    state_dict: data/models/feat_proj_image_graph/model_1.pt

dataset:
  catalogue:
    names: &csv_file data/processed/proj/test.csv
    modalities: [text]
    data_dir: &data_dir data/processed/complete_embeddings
  test:
    names: *csv_file
    modalities: [image]
    data_dir: *data_dir
dataloader:
  batch_size: 128
  num_workers: 16
  shuffle: False
  drop_last: False

metrics:
  recall_at_1:
    type: RetrievalRecall
    params:
      top_k: 1
  recall_at_5:
    type: RetrievalRecall
    params:
      top_k: 5
  recall_at_10:
    type: RetrievalRecall
    params:
      top_k: 10
encoding:
  pbar: &pbar True
  device: &device cuda

test_loop:
  pbar: *pbar
  device: *device
out_dir: data/models/artwork_siamese_network_complete
